blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pages'
urlpatterns = [
    path('', views.BlogList.as_view() , name='index'),
    path('<int:page_id>/', views.page, name='blog'),
    path('add/', views.blog_add, name='blog_add'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=50)
    image = models.ImageField(upload_to='uploads/', height_field=None, width_field=None, max_length=None)
    text = models.TextField()
    
    def __str__(self):
        return self.title

pages/forms.py
from django.forms import ModelForm
from .models import Blog

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'author', 'image','text']

pages/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from .forms import BlogForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
# Create your views here.
class BlogList(ListView):
    model = Blog
    context_object_name = 'blogs'
    paginate_by = 3 # adds a paginator and a page_obj to the context
    template_name='pages/index.html'
    
'''   
def index(request):
    blogs = Blog.objects.all()
    paaginator = Paginator(blogs, 3)
    
    return render(request, 'pages/index.html', {'blogs':blogs})
'''
def page(request, page_id):
    blog = get_object_or_404(Blog, pk=page_id)
    return render(request, 'pages/blog.html', {'blog':blog})

def blog_add(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('pages:index')
    else:
        form = BlogForm()
        context = {'form':form}
        return render(request, 'pages/blog_add.html', context)

pages/templates/pages/base.html
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% block content %} {% endblock content %}
    </body>
</html>

pages/templates/pages/blog.html
{% extends 'pages/base.html' %}
{% block title %}{{blog.title}}{% endblock title %}
{% block content %}
<h3>{{blog.title}}</h3>
<p>Written by {{blog.author}}</p>
<p>{{blog.text}}</p>
{% endblock content %}

pages/templates/pages/blog_add.html
{% extends 'pages/base.html' %}
{% block content %}
<form enctype="multipart/form-data" action="{% url 'pages:blog_add' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Post Blog">
</form>
{% endblock content %}

pages/templates/pages/index.html
{% extends 'pages/base.html' %}
{% block title %}blogs{% endblock title %}
{% block content %}
<h3>Welcome to blogs </h3>
<ul>
    {% for blog in blogs %}
    <ul>
        <li>{{blog.title}} by {{blog.author}}</li>
        <li>{{blog.text|slice:'300'}}...<a href='{% url "pages:blog" blog.id %}'>Read more</a></a></li>
        <li>
            <img "{{ blog.image.url }}">
    </ul>
    {% endfor %}
</ul>
<p><a href="{% url 'pages:blog_add' %}">Add new blog</a></p>
{% include 'pages/pagination.html' %} {# includes the template #}

{% endblock content %}

pages/templates/pages/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>